#pragma once

#include <stdlib.h>

static const char* worldgen_biome_entries[] = {
    "badlands",
    "bamboo_jungle",
    "basalt_deltas",
    "beach",
    "birch_forest",
    "cherry_grove",
    "cold_ocean",
    "crimson_forest",
    "dark_forest",
    "deep_cold_ocean",
    "deep_dark",
    "deep_frozen_ocean",
    "deep_lukewarm_ocean",
    "deep_ocean",
    "desert",
    "dripstone_caves",
    "end_barrens",
    "end_highlands",
    "end_midlands",
    "eroded_badlands",
    "flower_forest",
    "forest",
    "frozen_ocean",
    "frozen_peaks",
    "frozen_river",
    "grove",
    "ice_spikes",
    "jagged_peaks",
    "jungle",
    "lukewarm_ocean",
    "lush_caves",
    "mangrove_swamp",
    "meadow",
    "mushroom_fields",
    "nether_wastes",
    "ocean",
    "old_growth_birch_forest",
    "old_growth_pine_taiga",
    "old_growth_spruce_taiga",
    "pale_garden",
    "plains",
    "river",
    "savanna",
    "savanna_plateau",
    "small_end_islands",
    "snowy_beach",
    "snowy_plains",
    "snowy_slopes",
    "snowy_taiga",
    "soul_sand_valley",
    "sparse_jungle",
    "stony_peaks",
    "stony_shore",
    "sunflower_plains",
    "swamp",
    "taiga",
    "the_end",
    "the_void",
    "warm_ocean",
    "warped_forest",
    "windswept_forest",
    "windswept_gravelly_hills",
    "windswept_hills",
    "windswept_savanna",
    "wooded_badlands",
    NULL
};

static const char* damage_type_entries[] = {
    "arrow",
    "bad_respawn_point",
    "cactus",
    "campfire",
    "cramming",
    "dragon_breath",
    "drown",
    "dry_out",
    "ender_pearl",
    "explosion",
    "fall",
    "falling_anvil",
    "falling_block",
    "falling_stalactite",
    "fireball",
    "fireworks",
    "fly_into_wall",
    "freeze",
    "generic",
    "generic_kill",
    "hot_floor",
    "in_fire",
    "in_wall",
    "indirect_magic",
    "lava",
    "lightning_bolt",
    "mace_smash",
    "magic",
    "mob_attack",
    "mob_attack_no_aggro",
    "mob_projectile",
    "on_fire",
    "out_of_world",
    "outside_border",
    "player_attack",
    "player_explosion",
    "sonic_boom",
    "spit",
    "stalagmite",
    "starve",
    "sting",
    "sweet_berry_bush",
    "thorns",
    "thrown",
    "trident",
    "unattributed_fireball",
    "wind_charge",
    "wither",
    "wither_skull",
    NULL
};

static const char* chat_type_entries[] = {
    "chat",
    "emote_command",
    "msg_command_incoming",
    "msg_command_outgoing",
    "say_command",
    "team_msg_command_incoming",
    "team_msg_command_outgoing",
    NULL
};

static const char* dimension_type_entries[] = {
    "overworld",
    "overworld_caves",
    "the_end",
    "the_nether",
    NULL
};

static const char* cat_variant_entries[] = {
    "all_black",
    "black",
    "british_shorthair",
    "calico",
    "jellie",
    "persian",
    "ragdoll",
    "red",
    "siamese",
    "tabby",
    "white",
    NULL
};

static const char* chicken_variant_entries[] = {
    "cold",
    "temperate",
    "warm",
    NULL
};

static const char* cow_variant_entries[] = {
    "cold",
    "temperate",
    "warm",
    NULL
};

static const char* frog_variant_entries[] = {
    "cold",
    "temperate",
    "warm",
    NULL
};

static const char* painting_variant_entries[] = {
    "alban",
    "aztec",
    "aztec2",
    "backyard",
    "baroque",
    "bomb",
    "bouquet",
    "burning_skull",
    "bust",
    "cavebird",
    "changing",
    "cotan",
    "courbet",
    "creebet",
    "donkey_kong",
    "earth",
    "endboss",
    "fern",
    "fighters",
    "finding",
    "fire",
    "graham",
    "humble",
    "kebab",
    "lowmist",
    "match",
    "meditative",
    "orb",
    "owlemons",
    "passage",
    "pigscene",
    "plant",
    "pointer",
    "pond",
    "pool",
    "prairie_ride",
    "sea",
    "skeleton",
    "skull_and_roses",
    "stage",
    "sunflowers",
    "sunset",
    "tides",
    "unpacked",
    "void",
    "wanderer",
    "wasteland",
    "water",
    "wind",
    "wither",
    NULL
};

static const char* pig_variant_entries[] = {
    "cold",
    "temperate",
    "warm",
    NULL
};

static const char* wolf_sound_variant_entries[] = {
    "angry",
    "big",
    "classic",
    "cute",
    "grumpy",
    "puglin",
    "sad",
    NULL
};

static const char* wolf_variant_entries[] = {
    "ashen",
    "black",
    "chestnut",
    "pale",
    "rusty",
    "snowy",
    "spotted",
    "striped",
    "woods",
    NULL
};

struct RegistryPair {
    const char* registry_name;
    const char** entries;
};

static struct RegistryPair registries[] = {
    { "minecraft:worldgen/biome",     worldgen_biome_entries    },
    { "minecraft:damage_type",        damage_type_entries       },
    { "minecraft:chat_type",          chat_type_entries         },
    { "minecraft:dimension_type",     dimension_type_entries    },
    { "minecraft:cat_variant",        cat_variant_entries       },
    { "minecraft:chicken_variant",    chicken_variant_entries   },
    { "minecraft:cow_variant",        cow_variant_entries       },
    { "minecraft:frog_variant",       frog_variant_entries      },
    { "minecraft:painting_variant",   painting_variant_entries  },
    { "minecraft:pig_variant",        pig_variant_entries       },
    { "minecraft:wolf_sound_variant", wolf_sound_variant_entries},
    { "minecraft:wolf_variant",       wolf_variant_entries      },
    { NULL,                           NULL                      }
};

typedef enum {
    ET_ACACIA_BOAT,
    ET_ACACIA_CHEST_BOAT,
    ET_ALLAY,
    ET_AREA_EFFECT_CLOUD,
    ET_ARMADILLO,
    ET_ARMOR_STAND,
    ET_ARROW,
    ET_AXOLOTL,
    ET_BAMBOO_CHEST_RAFT,
    ET_BAMBOO_RAFT,
    ET_BAT,
    ET_BEE,
    ET_BIRCH_BOAT,
    ET_BIRCH_CHEST_BOAT,
    ET_BLAZE,
    ET_BLOCK_DISPLAY,
    ET_BOGGED,
    ET_BREEZE,
    ET_BREEZE_WIND_CHARGE,
    ET_CAMEL,
    ET_CAT,
    ET_CAVE_SPIDER,
    ET_CHERRY_BOAT,
    ET_CHERRY_CHEST_BOAT,
    ET_CHEST_MINECART,
    ET_CHICKEN,
    ET_COD,
    ET_COMMAND_BLOCK_MINECART,
    ET_COW,
    ET_CREAKING,
    ET_CREEPER,
    ET_DARK_OAK_BOAT,
    ET_DARK_OAK_CHEST_BOAT,
    ET_DOLPHIN,
    ET_DONKEY,
    ET_DRAGON_FIREBALL,
    ET_DROWNED,
    ET_EGG,
    ET_ELDER_GUARDIAN,
    ET_ENDERMAN,
    ET_ENDERMITE,
    ET_ENDER_DRAGON,
    ET_ENDER_PEARL,
    ET_END_CRYSTAL,
    ET_EVOKER,
    ET_EVOKER_FANGS,
    ET_EXPERIENCE_BOTTLE,
    ET_EXPERIENCE_ORB,
    ET_EYE_OF_ENDER,
    ET_FALLING_BLOCK,
    ET_FIREBALL,
    ET_FIREWORK_ROCKET,
    ET_FOX,
    ET_FROG,
    ET_FURNACE_MINECART,
    ET_GHAST,
    ET_GIANT,
    ET_GLOW_ITEM_FRAME,
    ET_GLOW_SQUID,
    ET_GOAT,
    ET_GUARDIAN,
    ET_HOGLIN,
    ET_HOPPER_MINECART,
    ET_HORSE,
    ET_HUSK,
    ET_ILLUSIONER,
    ET_INTERACTION,
    ET_IRON_GOLEM,
    ET_ITEM,
    ET_ITEM_DISPLAY,
    ET_ITEM_FRAME,
    ET_JUNGLE_BOAT,
    ET_JUNGLE_CHEST_BOAT,
    ET_LEASH_KNOT,
    ET_LIGHTNING_BOLT,
    ET_LLAMA,
    ET_LLAMA_SPIT,
    ET_MAGMA_CUBE,
    ET_MANGROVE_BOAT,
    ET_MANGROVE_CHEST_BOAT,
    ET_MARKER,
    ET_MINECART,
    ET_MOOSHROOM,
    ET_MULE,
    ET_OAK_BOAT,
    ET_OAK_CHEST_BOAT,
    ET_OCELOT,
    ET_OMINOUS_ITEM_SPAWNER,
    ET_PAINTING,
    ET_PALE_OAK_BOAT,
    ET_PALE_OAK_CHEST_BOAT,
    ET_PANDA,
    ET_PARROT,
    ET_PHANTOM,
    ET_PIG,
    ET_PIGLIN,
    ET_PIGLIN_BRUTE,
    ET_PILLAGER,
    ET_POLAR_BEAR,
    ET_SPLASH_POTION,
    ET_LINGERING_POTION,
    ET_PUFFERFISH,
    ET_RABBIT,
    ET_RAVAGER,
    ET_SALMON,
    ET_SHEEP,
    ET_SHULKER,
    ET_SHULKER_BULLET,
    ET_SILVERFISH,
    ET_SKELETON,
    ET_SKELETON_HORSE,
    ET_SLIME,
    ET_SMALL_FIREBALL,
    ET_SNIFFER,
    ET_SNOWBALL,
    ET_SNOW_GOLEM,
    ET_SPAWNER_MINECART,
    ET_SPECTRAL_ARROW,
    ET_SPIDER,
    ET_SPRUCE_BOAT,
    ET_SPRUCE_CHEST_BOAT,
    ET_SQUID,
    ET_STRAY,
    ET_STRIDER,
    ET_TADPOLE,
    ET_TEXT_DISPLAY,
    ET_TNT,
    ET_TNT_MINECART,
    ET_TRADER_LLAMA,
    ET_TRIDENT,
    ET_TROPICAL_FISH,
    ET_TURTLE,
    ET_VEX,
    ET_VILLAGER,
    ET_VINDICATOR,
    ET_WANDERING_TRADER,
    ET_WARDEN,
    ET_WIND_CHARGE,
    ET_WITCH,
    ET_WITHER,
    ET_WITHER_SKELETON,
    ET_WITHER_SKULL,
    ET_WOLF,
    ET_ZOGLIN,
    ET_ZOMBIE,
    ET_ZOMBIE_HORSE,
    ET_ZOMBIE_VILLAGER,
    ET_ZOMBIFIED_PIGLIN,
    ET_PLAYER,
    ET_FISHING_BOBBER,
} EntityType;
